// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuP-YqppkSpSxc4TEASM8X4owi1X4mvi0',
    appId: '1:1007030617651:web:3f12b49b3b18d469b88546',
    messagingSenderId: '1007030617651',
    projectId: 'team-task-app-5a91c',
    authDomain: 'team-task-app-5a91c.firebaseapp.com',
    storageBucket: 'team-task-app-5a91c.firebasestorage.app',
    measurementId: 'G-NZ607L7THP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS_v5-zYeEhKu4FSTIytc0mRIwyTB3KtM',
    appId: '1:1007030617651:android:cd7682ce7c11c864b88546',
    messagingSenderId: '1007030617651',
    projectId: 'team-task-app-5a91c',
    storageBucket: 'team-task-app-5a91c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuumGfEtoHPMWLga79jQRzKIkvDh_YU34',
    appId: '1:1007030617651:ios:4782b3d6b07d1c4ab88546',
    messagingSenderId: '1007030617651',
    projectId: 'team-task-app-5a91c',
    storageBucket: 'team-task-app-5a91c.firebasestorage.app',
    iosBundleId: 'com.example.teamTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuumGfEtoHPMWLga79jQRzKIkvDh_YU34',
    appId: '1:1007030617651:ios:4782b3d6b07d1c4ab88546',
    messagingSenderId: '1007030617651',
    projectId: 'team-task-app-5a91c',
    storageBucket: 'team-task-app-5a91c.firebasestorage.app',
    iosBundleId: 'com.example.teamTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuP-YqppkSpSxc4TEASM8X4owi1X4mvi0',
    appId: '1:1007030617651:web:0ba595e128f32872b88546',
    messagingSenderId: '1007030617651',
    projectId: 'team-task-app-5a91c',
    authDomain: 'team-task-app-5a91c.firebaseapp.com',
    storageBucket: 'team-task-app-5a91c.firebasestorage.app',
    measurementId: 'G-3ZX2E1RYDS',
  );
}
